name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Ibalik natin sa latest para mas mabilis mahanap ang action

    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1 # Ito ang tamang version tag
        with:
          buildozer_version: stable
          command: buildozer android debug
